In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [2]:
base_census = pd.read_csv("../Machine Learning e Data Science com Python de A à Z/Bases de dados/census.csv")

In [15]:
X_census = base_census.iloc[:, 0:14].values
Y_census = base_census.iloc[:, 14].values

In [16]:
X_census[0]

array([39, ' State-gov', 77516, ' Bachelors', 13, ' Never-married',
       ' Adm-clerical', ' Not-in-family', ' White', ' Male', 2174, 0, 40,
       ' United-States'], dtype=object)

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
LabelEncoder_test = LabelEncoder()
# Aqui, precisamos transformar dados string em dados num[ericos para oder trabalhar, algo muito similar ao que fizemos em trnasformar 1 em aceito, 0 em negado e 2 em duvidoso na primeira etapa do projeto

In [19]:
teste = LabelEncoder_test.fit_transform(X_census[:, 1]) 
# Transformando a coluna 1 do X_census em números

In [20]:
X_census[:, 1]

array([' State-gov', ' Self-emp-not-inc', ' Private', ..., ' Private',
       ' Private', ' Self-emp-inc'], dtype=object)

In [21]:
teste

array([7, 6, 4, ..., 4, 4, 5])

In [22]:
X_census[0]

array([39, ' State-gov', 77516, ' Bachelors', 13, ' Never-married',
       ' Adm-clerical', ' Not-in-family', ' White', ' Male', 2174, 0, 40,
       ' United-States'], dtype=object)

In [23]:
LabelEncoder_workclass = LabelEncoder()
LabelEncoder_education = LabelEncoder()
LabelEncoder_marital = LabelEncoder()
LabelEncoder_occupation = LabelEncoder()
LabelEncoder_relationship = LabelEncoder()
LabelEncoder_race = LabelEncoder()
LabelEncoder_sex = LabelEncoder()
LabelEncoder_country = LabelEncoder()

In [24]:
X_census[:, 1] = LabelEncoder_workclass.fit_transform(X_census[:, 1])
X_census[:, 3] = LabelEncoder_education.fit_transform(X_census[:, 3])
X_census[:, 5] = LabelEncoder_marital.fit_transform(X_census[:, 5])
X_census[:, 6] = LabelEncoder_occupation.fit_transform(X_census[:, 6])
X_census[:, 7] = LabelEncoder_relationship.fit_transform(X_census[:, 7])
X_census[:, 8] = LabelEncoder_race.fit_transform(X_census[:, 8])
X_census[:, 9] = LabelEncoder_sex.fit_transform(X_census[:, 9])
X_census[:, 13] = LabelEncoder_country.fit_transform(X_census[:, 13])

In [25]:
X_census[0]

array([39, 7, 77516, 9, 13, 4, 1, 1, 4, 1, 2174, 0, 40, 39], dtype=object)

In [26]:
X_census

array([[39, 7, 77516, ..., 0, 40, 39],
       [50, 6, 83311, ..., 0, 13, 39],
       [38, 4, 215646, ..., 0, 40, 39],
       ...,
       [58, 4, 151910, ..., 0, 40, 39],
       [22, 4, 201490, ..., 0, 20, 39],
       [52, 5, 287927, ..., 0, 40, 39]], dtype=object)